### ISSUE TITLE
open pdf ,  print pdf not working

### ISSUE THREAD

**Issue by ayoubAnbara** [ngdevelop-tech/angular-8-export-pdf#7]
i open your web site:
https://online-resume-builder.netlify.app/
in google chrome, when i click on buttons open pdf , print pdf nothing happens

**Comment by ngdevelop-tech** [comment]
Hi @ayoub96anbara, 
I have tested it on my browser, and it is working fine. 

Can you verify whether in your browser popup is blocked or not?, If you are using a chrome browser then you will find a popup block icon in search bar. Allow popups to open pdf and print pdf. 

If a pop-up is allowed then let me know, is there any error on console. if it is then please share the screenshot for the same.

**Comment by ngdevelop-tech** [comment]
@ayoub96anbara, haven't received any reply from you. So closing this issue. Please let me know, If you still facing this issue.
